import { Country } from '../types/game';

function mapsUrl(name: string): string {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(name)}`;
}

export const FALLBACK_COUNTRIES: Country[] = [
  { name: 'France', alpha2: 'FR', mapUrl: mapsUrl('France'), region: 'Europe' },
  { name: 'Japan', alpha2: 'JP', mapUrl: mapsUrl('Japan'), region: 'Asia' },
  { name: 'Brazil', alpha2: 'BR', mapUrl: mapsUrl('Brazil'), region: 'Americas' },
  { name: 'Canada', alpha2: 'CA', mapUrl: mapsUrl('Canada'), region: 'Americas' },
  { name: 'Australia', alpha2: 'AU', mapUrl: mapsUrl('Australia'), region: 'Oceania' },
  { name: 'Germany', alpha2: 'DE', mapUrl: mapsUrl('Germany'), region: 'Europe' },
  { name: 'Italy', alpha2: 'IT', mapUrl: mapsUrl('Italy'), region: 'Europe' },
  { name: 'Spain', alpha2: 'ES', mapUrl: mapsUrl('Spain'), region: 'Europe' },
  { name: 'United Kingdom', alpha2: 'GB', mapUrl: mapsUrl('United Kingdom'), region: 'Europe' },
  { name: 'United States', alpha2: 'US', mapUrl: mapsUrl('United States'), region: 'Americas' },
  { name: 'Argentina', alpha2: 'AR', mapUrl: mapsUrl('Argentina'), region: 'Americas' },
  { name: 'Mexico', alpha2: 'MX', mapUrl: mapsUrl('Mexico'), region: 'Americas' },
  { name: 'South Africa', alpha2: 'ZA', mapUrl: mapsUrl('South Africa'), region: 'Africa' },
  { name: 'Egypt', alpha2: 'EG', mapUrl: mapsUrl('Egypt'), region: 'Africa' },
  { name: 'India', alpha2: 'IN', mapUrl: mapsUrl('India'), region: 'Asia' },
  { name: 'China', alpha2: 'CN', mapUrl: mapsUrl('China'), region: 'Asia' },
  { name: 'South Korea', alpha2: 'KR', mapUrl: mapsUrl('South Korea'), region: 'Asia' },
  { name: 'Greece', alpha2: 'GR', mapUrl: mapsUrl('Greece'), region: 'Europe' },
  { name: 'Portugal', alpha2: 'PT', mapUrl: mapsUrl('Portugal'), region: 'Europe' },
  { name: 'Sweden', alpha2: 'SE', mapUrl: mapsUrl('Sweden'), region: 'Europe' },
  { name: 'Norway', alpha2: 'NO', mapUrl: mapsUrl('Norway'), region: 'Europe' },
  { name: 'Finland', alpha2: 'FI', mapUrl: mapsUrl('Finland'), region: 'Europe' },
  { name: 'Switzerland', alpha2: 'CH', mapUrl: mapsUrl('Switzerland'), region: 'Europe' },
  { name: 'Netherlands', alpha2: 'NL', mapUrl: mapsUrl('Netherlands'), region: 'Europe' },
  { name: 'Belgium', alpha2: 'BE', mapUrl: mapsUrl('Belgium'), region: 'Europe' },
  { name: 'Ireland', alpha2: 'IE', mapUrl: mapsUrl('Ireland'), region: 'Europe' },
  { name: 'New Zealand', alpha2: 'NZ', mapUrl: mapsUrl('New Zealand'), region: 'Oceania' },
  { name: 'Chile', alpha2: 'CL', mapUrl: mapsUrl('Chile'), region: 'Americas' },
  { name: 'Colombia', alpha2: 'CO', mapUrl: mapsUrl('Colombia'), region: 'Americas' },
  { name: 'Peru', alpha2: 'PE', mapUrl: mapsUrl('Peru'), region: 'Americas' },
  { name: 'Kenya', alpha2: 'KE', mapUrl: mapsUrl('Kenya'), region: 'Africa' },
  { name: 'Nigeria', alpha2: 'NG', mapUrl: mapsUrl('Nigeria'), region: 'Africa' },
  { name: 'Morocco', alpha2: 'MA', mapUrl: mapsUrl('Morocco'), region: 'Africa' },
  { name: 'Thailand', alpha2: 'TH', mapUrl: mapsUrl('Thailand'), region: 'Asia' },
  { name: 'Vietnam', alpha2: 'VN', mapUrl: mapsUrl('Vietnam'), region: 'Asia' },
  { name: 'Indonesia', alpha2: 'ID', mapUrl: mapsUrl('Indonesia'), region: 'Asia' },
  { name: 'Malaysia', alpha2: 'MY', mapUrl: mapsUrl('Malaysia'), region: 'Asia' },
  { name: 'Singapore', alpha2: 'SG', mapUrl: mapsUrl('Singapore'), region: 'Asia' },
  { name: 'Philippines', alpha2: 'PH', mapUrl: mapsUrl('Philippines'), region: 'Asia' },
  { name: 'Turkey', alpha2: 'TR', mapUrl: mapsUrl('Turkey'), region: 'Europe' },
  { name: 'Saudi Arabia', alpha2: 'SA', mapUrl: mapsUrl('Saudi Arabia'), region: 'Asia' },
  { name: 'United Arab Emirates', alpha2: 'AE', mapUrl: mapsUrl('United Arab Emirates'), region: 'Asia' },
  { name: 'Iceland', alpha2: 'IS', mapUrl: mapsUrl('Iceland'), region: 'Europe' },
  { name: 'Denmark', alpha2: 'DK', mapUrl: mapsUrl('Denmark'), region: 'Europe' },
  { name: 'Poland', alpha2: 'PL', mapUrl: mapsUrl('Poland'), region: 'Europe' },
  { name: 'Austria', alpha2: 'AT', mapUrl: mapsUrl('Austria'), region: 'Europe' },
  { name: 'Czechia', alpha2: 'CZ', mapUrl: mapsUrl('Czechia'), region: 'Europe' },
  { name: 'Croatia', alpha2: 'HR', mapUrl: mapsUrl('Croatia'), region: 'Europe' },
  { name: 'Jamaica', alpha2: 'JM', mapUrl: mapsUrl('Jamaica'), region: 'Americas' },
  { name: 'Cuba', alpha2: 'CU', mapUrl: mapsUrl('Cuba'), region: 'Americas' },
  { name: 'Uruguay', alpha2: 'UY', mapUrl: mapsUrl('Uruguay'), region: 'Americas' },
  { name: 'Costa Rica', alpha2: 'CR', mapUrl: mapsUrl('Costa Rica'), region: 'Americas' },
  { name: 'Panama', alpha2: 'PA', mapUrl: mapsUrl('Panama'), region: 'Americas' },
  { name: 'Ghana', alpha2: 'GH', mapUrl: mapsUrl('Ghana'), region: 'Africa' },
  { name: 'Senegal', alpha2: 'SN', mapUrl: mapsUrl('Senegal'), region: 'Africa' },
  { name: 'Ethiopia', alpha2: 'ET', mapUrl: mapsUrl('Ethiopia'), region: 'Africa' },
  { name: 'Nepal', alpha2: 'NP', mapUrl: mapsUrl('Nepal'), region: 'Asia' },
  { name: 'Mongolia', alpha2: 'MN', mapUrl: mapsUrl('Mongolia'), region: 'Asia' },
  { name: 'Fiji', alpha2: 'FJ', mapUrl: mapsUrl('Fiji'), region: 'Oceania' },
  { name: 'Madagascar', alpha2: 'MG', mapUrl: mapsUrl('Madagascar'), region: 'Africa' },
];
