import { Country } from '../types/game';

export const FALLBACK_COUNTRIES: Country[] = [
  { name: 'France', alpha2: 'FR', mapUrl: 'https://goo.gl/maps/g79ecQVSeih694nm9', region: 'Europe' },
  { name: 'Japan', alpha2: 'JP', mapUrl: 'https://goo.gl/maps/NGTLSCSrKvR2', region: 'Asia' },
  { name: 'Brazil', alpha2: 'BR', mapUrl: 'https://goo.gl/maps/waCKk2pmFqqPRKPB7', region: 'Americas' },
  { name: 'Canada', alpha2: 'CA', mapUrl: 'https://goo.gl/maps/jmOAS9AggR1JDsqE6', region: 'Americas' },
  { name: 'Australia', alpha2: 'AU', mapUrl: 'https://goo.gl/maps/DywA2bbmtCXJgahSt8', region: 'Oceania' },
  { name: 'Germany', alpha2: 'DE', mapUrl: 'https://goo.gl/maps/jD5Aj4CGuQ09GpO87', region: 'Europe' },
  { name: 'Italy', alpha2: 'IT', mapUrl: 'https://goo.gl/maps/bFAnEKvdAVMySXh56', region: 'Europe' },
  { name: 'Spain', alpha2: 'ES', mapUrl: 'https://goo.gl/maps/138JaZX6qRtWGAHa9', region: 'Europe' },
  { name: 'United Kingdom', alpha2: 'GB', mapUrl: 'https://goo.gl/maps/FoDtc3UKFdEHRygHA', region: 'Europe' },
  { name: 'United States', alpha2: 'US', mapUrl: 'https://goo.gl/maps/e8M246zY4BSjkack7', region: 'Americas' },
  { name: 'Argentina', alpha2: 'AR', mapUrl: 'https://goo.gl/maps/ZoxAYviYvyMmEZFLA', region: 'Americas' },
  { name: 'Mexico', alpha2: 'MX', mapUrl: 'https://goo.gl/maps/s5bg17MGfdPvRCRCA', region: 'Americas' },
  { name: 'South Africa', alpha2: 'ZA', mapUrl: 'https://goo.gl/maps/6cgRwSc2hRyCJRrY8', region: 'Africa' },
  { name: 'Egypt', alpha2: 'EG', mapUrl: 'https://goo.gl/maps/uoDRhXbsqdtgqiXB8', region: 'Africa' },
  { name: 'India', alpha2: 'IN', mapUrl: 'https://goo.gl/maps/WSk3fLwG4vtPQetp7', region: 'Asia' },
  { name: 'China', alpha2: 'CN', mapUrl: 'https://goo.gl/maps/p9qC6vgiFRRXzvJT7', region: 'Asia' },
  { name: 'South Korea', alpha2: 'KR', mapUrl: 'https://goo.gl/maps/7ecjaJfzoHBPyijd7', region: 'Asia' },
  { name: 'Greece', alpha2: 'GR', mapUrl: 'https://goo.gl/maps/LHGcAvuAnojfHGEd7', region: 'Europe' },
  { name: 'Portugal', alpha2: 'PT', mapUrl: 'https://goo.gl/maps/BaTBSycEZG2pNGSt9', region: 'Europe' },
  { name: 'Sweden', alpha2: 'SE', mapUrl: 'https://goo.gl/maps/iqygpUmGQ9JcHGgf9', region: 'Europe' },
  { name: 'Norway', alpha2: 'NO', mapUrl: 'https://goo.gl/maps/htGpttiUQbEm3Tm97', region: 'Europe' },
  { name: 'Finland', alpha2: 'FI', mapUrl: 'https://goo.gl/maps/HjgWDCNKGcBrmUA59', region: 'Europe' },
  { name: 'Switzerland', alpha2: 'CH', mapUrl: 'https://goo.gl/maps/uVuZwti3bvAR6zCe9', region: 'Europe' },
  { name: 'Netherlands', alpha2: 'NL', mapUrl: 'https://goo.gl/maps/JR673uVvxmDCriMS9', region: 'Europe' },
  { name: 'Belgium', alpha2: 'BE', mapUrl: 'https://goo.gl/maps/UQQvh8NVTnDxsvdCA', region: 'Europe' },
  { name: 'Ireland', alpha2: 'IE', mapUrl: 'https://goo.gl/maps/hwm3tC8CrBCTw2v29', region: 'Europe' },
  { name: 'New Zealand', alpha2: 'NZ', mapUrl: 'https://goo.gl/maps/44nRCS7xdSV39xCD8', region: 'Oceania' },
  { name: 'Chile', alpha2: 'CL', mapUrl: 'https://goo.gl/maps/XboxyAN1NmHHc2Pt9', region: 'Americas' },
  { name: 'Colombia', alpha2: 'CO', mapUrl: 'https://goo.gl/maps/RdwTG8vFnxVUhaBA7', region: 'Americas' },
  { name: 'Peru', alpha2: 'PE', mapUrl: 'https://goo.gl/maps/uDWEUaXNcZTng1icA', region: 'Americas' },
  { name: 'Kenya', alpha2: 'KE', mapUrl: 'https://goo.gl/maps/Ni9M5wcCxfqspnPt5', region: 'Africa' },
  { name: 'Nigeria', alpha2: 'NG', mapUrl: 'https://goo.gl/maps/LTHQmNS5cpvCyrYv8', region: 'Africa' },
  { name: 'Morocco', alpha2: 'MA', mapUrl: 'https://goo.gl/maps/6PETHuTJ7HzgtBCH8', region: 'Africa' },
  { name: 'Thailand', alpha2: 'TH', mapUrl: 'https://goo.gl/maps/hmPf1AsBGAtoqXvK9', region: 'Asia' },
  { name: 'Vietnam', alpha2: 'VN', mapUrl: 'https://goo.gl/maps/pfd9wfBiaqC9t8SV9', region: 'Asia' },
  { name: 'Indonesia', alpha2: 'ID', mapUrl: 'https://goo.gl/maps/9gfPupTUyyB9fdEG7', region: 'Asia' },
  { name: 'Malaysia', alpha2: 'MY', mapUrl: 'https://goo.gl/maps/jt5uv4eA8gHk9qY76', region: 'Asia' },
  { name: 'Singapore', alpha2: 'SG', mapUrl: 'https://goo.gl/maps/973gf4ue8cM5W8tB9', region: 'Asia' },
  { name: 'Philippines', alpha2: 'PH', mapUrl: 'https://goo.gl/maps/1eA68HrfqTa8t8vGA', region: 'Asia' },
  { name: 'Turkey', alpha2: 'TR', mapUrl: 'https://goo.gl/maps/dXwbubrBcXMv3aZz8', region: 'Europe' },
  { name: 'Saudi Arabia', alpha2: 'SA', mapUrl: 'https://goo.gl/maps/5PSj6rTGeRo7z3NPA', region: 'Asia' },
  { name: 'United Arab Emirates', alpha2: 'AE', mapUrl: 'https://goo.gl/maps/vRhRVspsGQPdHgqQA', region: 'Asia' },
  { name: 'Iceland', alpha2: 'IS', mapUrl: 'https://goo.gl/maps/WxF3eNuQ2kG9c4Dk6', region: 'Europe' },
  { name: 'Denmark', alpha2: 'DK', mapUrl: 'https://goo.gl/maps/ugP5ucqVs2ykn8L79', region: 'Europe' },
  { name: 'Poland', alpha2: 'PL', mapUrl: 'https://goo.gl/maps/g7McgpH63dpqT2yo8', region: 'Europe' },
  { name: 'Austria', alpha2: 'AT', mapUrl: 'https://goo.gl/maps/pCWpTgmi8nxc5DfH9', region: 'Europe' },
  { name: 'Czechia', alpha2: 'CZ', mapUrl: 'https://goo.gl/maps/47dmopLbt9ZGN1Z5A', region: 'Europe' },
  { name: 'Croatia', alpha2: 'HR', mapUrl: 'https://goo.gl/maps/DNor7cQv5qGhAEUP9', region: 'Europe' },
  { name: 'Jamaica', alpha2: 'JM', mapUrl: 'https://goo.gl/maps/Z8mhaPyNuJUWDuxt8', region: 'Americas' },
  { name: 'Cuba', alpha2: 'CU', mapUrl: 'https://goo.gl/maps/4p7tECB6eeyfPauUA', region: 'Americas' },
  { name: 'Uruguay', alpha2: 'UY', mapUrl: 'https://goo.gl/maps/tiQCvtuLuhb19zEp9', region: 'Americas' },
  { name: 'Costa Rica', alpha2: 'CR', mapUrl: 'https://goo.gl/maps/rswjhDYkC2t9tq34A', region: 'Americas' },
  { name: 'Panama', alpha2: 'PA', mapUrl: 'https://goo.gl/maps/sEN7NxnwEbscafAHA', region: 'Americas' },
  { name: 'Ghana', alpha2: 'GH', mapUrl: 'https://goo.gl/maps/AvyCNpzsCLuQFrNx9', region: 'Africa' },
  { name: 'Senegal', alpha2: 'SN', mapUrl: 'https://goo.gl/maps/JpAuFwwocsrBfvtbA', region: 'Africa' },
  { name: 'Ethiopia', alpha2: 'ET', mapUrl: 'https://goo.gl/maps/nCvNweQAGcMQfM7S8', region: 'Africa' },
  { name: 'Nepal', alpha2: 'NP', mapUrl: 'https://goo.gl/maps/544kSdkiY8b9hX9b8', region: 'Asia' },
  { name: 'Mongolia', alpha2: 'MN', mapUrl: 'https://goo.gl/maps/Tf77KzD54Yd3M1Wf6', region: 'Asia' },
  { name: 'Fiji', alpha2: 'FJ', mapUrl: 'https://goo.gl/maps/r92jtfX1FRTr78ST6', region: 'Oceania' },
  { name: 'Madagascar', alpha2: 'MG', mapUrl: 'https://goo.gl/maps/p642Zq94qGkRz95V7', region: 'Africa' },
];
